import {
    HiUserCircle,
    HiAdjustments,
    HiClipboardList,
    HiDocumentReport,
    HiCurrencyDollar,
    HiCreditCard,
    HiChartPie,
    HiChartBar,
    HiChartSquareBar,
    HiDatabase,
    HiBell,
    HiCalendar,
    HiCheckCircle,
    HiExclamationCircle,
    HiInformationCircle,
    HiLockClosed,
    HiLockOpen,
    HiMail,
    HiPhone,
    HiSearch,
    HiShieldCheck,
    HiStatusOnline,
    HiSupport,
    HiTemplate,
    HiTrash,
    HiUserGroup,
    HiViewGrid,
    HiHeart,
    HiClipboardCheck,
    HiCash,
    HiDocumentText,
  } from "react-icons/hi";
  
  const iconMap: Record<string, React.ElementType> = {
    hiUser: HiUserCircle,
    hiAdjustments: HiAdjustments,
    hiClipboard: HiClipboardList,
    hiReport: HiDocumentReport,
    hiDollar: HiCurrencyDollar,
    hiCreditCard: HiCreditCard,
    hiPieChart: HiChartPie,
    hiBarChart: HiChartBar,
    hiSquareChart: HiChartSquareBar,
    hiDatabase: HiDatabase,
    hiNotifications: HiBell,
    hiCalendar: HiCalendar,
    hiCheckCircle: HiCheckCircle,
    hiExclamationCircle: HiExclamationCircle,
    hiInfoCircle: HiInformationCircle,
    hiLockClosed: HiLockClosed,
    hiLockOpen: HiLockOpen,
    hiMail: HiMail,
    hiPhone: HiPhone,
    hiSearch: HiSearch,
    hiShieldCheck: HiShieldCheck,
    hiStatusOnline: HiStatusOnline,
    hiSupport: HiSupport,
    hiTemplate: HiTemplate,
    hiTrash: HiTrash,
    hiUserGroup: HiUserGroup,
    hiGrid: HiViewGrid,
    hiHeart: HiHeart,
    hiClipboardCheck: HiClipboardCheck,
    hiCash: HiCash,
    hiDocumentText: HiDocumentText,
  };
  
  export default iconMap;
  