import React, { useEffect, useState } from "react";
import { HiHome, HiChartPie, HiHashtag } from "react-icons/hi";
import SidebarCollapse from "./sidebar-collapse";
import SidebarGroup from "./sidebar-group";
import { SidebarNavLink } from "./ui-wrappers";
import { fetchDataWithoutStore } from "../api/api";
import { Sidebar } from "flowbite-react";

// Mapping of icon names to actual SVG components
const iconMap: { [key: string]: React.FC<React.SVGProps<SVGSVGElement>> } = {
  "home-icon": HiHome,
  "dashboard-icon": HiChartPie,
  "dashboards-icon": HiChartPie,
  "hashtag-icon": HiHashtag,
  // Add more mappings as needed
};

// Default configuration as a fallback
const defaultSidebarConfig = {
  system: {
    home: {
      title: "Home",
      icon: "home-icon",
      dashboard: "/",
    },
    menu: [],
  },
  user: {
    menu: [],
  },
};

const renderSidebarMenu = (config: any) => {
  const homeConfig = config.system?.home;
  const systemMenu = config.system?.menu || [];
  const userMenu = config.user?.menu || [];

  // Render Home link inside Sidebar.ItemGroup
  const homeLink = homeConfig ? (
    <Sidebar.ItemGroup key="home-group">
      <SidebarNavLink
        to={homeConfig.dashboard}
        icon={iconMap[homeConfig.icon] || HiHome} // Provide a fallback icon
      >
        {homeConfig.title}
      </SidebarNavLink>
    </Sidebar.ItemGroup>
  ) : null;

  // Render the System group
  const systemGroup =
    systemMenu.length > 0 ? (
      <SidebarGroup key="system-group" title="System">
        {systemMenu.map((item: any, index: number) => {
          const Icon = iconMap[item.icon] || HiChartPie; // Provide a fallback icon
          if (item.dashboards && item.dashboards.length > 0) {
            return (
              <SidebarCollapse
                key={index}
                icon={Icon}
                label={item.title}
                paths={item.dashboards.map((d: any) => d.dashboard)}
              >
                {item.dashboards.map((nestedItem: any, nestedIndex: number) => (
                  <SidebarNavLink
                    key={nestedIndex}
                    to={nestedItem.dashboard}
                    icon={iconMap[nestedItem.icon] || HiChartPie} // Provide a fallback icon
                  >
                    {nestedItem.title}
                  </SidebarNavLink>
                ))}
              </SidebarCollapse>
            );
          } else {
            return (
              <SidebarNavLink key={index} to={item.dashboard} icon={Icon}>
                {item.title}
              </SidebarNavLink>
            );
          }
        })}
      </SidebarGroup>
    ) : null;

  // Render the User group
  const userGroup =
    userMenu.length > 0 ? (
      <SidebarGroup key="user-group" title="User">
        {userMenu.map((item: any, index: number) => {
          const Icon = iconMap[item.icon] || HiChartPie; // Provide a fallback icon
          if (item.dashboards && item.dashboards.length > 0) {
            return (
              <SidebarCollapse
                key={index}
                icon={Icon}
                label={item.title}
                paths={item.dashboards.map((d: any) => d.dashboard)}
              >
                {item.dashboards.map((nestedItem: any, nestedIndex: number) => (
                  <SidebarNavLink
                    key={nestedIndex}
                    to={nestedItem.dashboard}
                    icon={iconMap[nestedItem.icon] || HiChartPie} // Provide a fallback icon
                  >
                    {nestedItem.title}
                  </SidebarNavLink>
                ))}
              </SidebarCollapse>
            );
          } else {
            return (
              <SidebarNavLink key={index} to={item.dashboard} icon={Icon}>
                {item.title}
              </SidebarNavLink>
            );
          }
        })}
      </SidebarGroup>
    ) : null;

  return (
    <>
      {homeLink}
      {systemGroup}
      {userGroup}
    </>
  );
};

const SystemSidebar = () => {
  const [sidebarConfig, setSidebarConfig] = useState(defaultSidebarConfig);

  useEffect(() => {
    const loadSidebarConfig = async () => {
      try {
        const config = await fetchDataWithoutStore("/navigation");
        console.log("Fetched config:", config);
        setSidebarConfig(config || defaultSidebarConfig);
      } catch (error) {
        console.error("Failed to load sidebar config", error);
        setSidebarConfig(defaultSidebarConfig);
      }
    };

    loadSidebarConfig();
  }, []);

  return <>{renderSidebarMenu(sidebarConfig)}</>;
};

export default SystemSidebar;

/* 
Example JSX structure generated by this code based on the updated JSON:

<Sidebar.ItemGroup>
  <SidebarNavLink to="/" icon={HiHome}>
    Home
  </SidebarNavLink>
</Sidebar.ItemGroup>

<SidebarGroup title="System">
  <SidebarNavLink to="/dashboard" icon={HiChartPie}>
    {API} DB 1
  </SidebarNavLink>
  <SidebarCollapse icon={HiChartPie} label="{API} More" paths={["/a", "/b", "/c", "/d", "/api"]}>
    <SidebarNavLink to="/a" icon={HiChartPie}>
      Sub Dashboard 1
    </SidebarNavLink>
    <SidebarNavLink to="/b" icon={HiChartPie}>
      Sub Dashboard 2
    </SidebarNavLink>
    <SidebarNavLink to="/c" icon={HiChartPie}>
      Sub Dashboard 3
    </SidebarNavLink>
    <SidebarNavLink to="/d" icon={HiChartPie}>
      Sub Dashboard 4
    </SidebarNavLink>
    <SidebarNavLink to="/api" icon={HiHashtag}>
      APIs
    </SidebarNavLink>
  </SidebarCollapse>
</SidebarGroup>

<SidebarGroup title="User">
  <!-- Currently empty, but ready for future user-specific items -->
</SidebarGroup>

*/
